{{- if .Values.gatewayClass.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: {{ include "envoy-gateway.fullname" . }}
  labels:
{{ include "envoy-gateway.labels" . | indent 4 }}
spec:
  controllerName: {{ .Values.gatewayClass.controllerName }}
{{- end }}
