{{- if .Values.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ include "envoy-gateway.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
{{ include "envoy-gateway.labels" . | indent 4 }}
  {{- with .Values.gateway.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  gatewayClassName: {{ include "envoy-gateway.fullname" . }}
  listeners:
    {{- toYaml .Values.gateway.listeners | nindent 4 }}
{{- end }}
